repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7

- repo: https://gist.github.com/bsamseth/0abbcee0655e8023abc63c2c2b27c122
  rev: 73150949ede04ada8f8996b13a92c371e5c90404
  hooks:
  - id: isort
    language_version: python3.7

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-yaml
