language: cpp
compiler: gcc
dist: xenial
notifications:
  email: false

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.7-dev
  apt:
    packages: lcov

before_install:
  - pyenv global $(pyenv whence 2to3)  # activate all python versions
  - python3 --version
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90

  # Install coverals gem for uploading coverage to coveralls.
  - gem install coveralls-lcov

  # Install Python virtual environment manager.
  - pip install pipenv

before_script:
  - lcov --version
  - gcov --version
  - g++ --version

script:
  - pipenv install
  - CMAKE_BUILD_TYPE=Coverage pipenv run python setup.py test

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '*/tests/*' '/usr/*' '*/external/*' '/Applications/*'--output-file coverage.info # filter system-files
  - lcov --list coverage.info
  - coveralls-lcov coverage_out.info  # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

