language: cpp
dist: xenial
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - lcov
            - g++-7
            # MPI
            - openmpi-bin
            - openssh-client
            - openssh-server
            - libopenmpi-dev
      env:
        - CC7="gcc-7"
        - CXX7="g++-7"


before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ `which $CXX7` 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  # Disable CC and CXX, which interferes with MPI
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - lcov --version
  - gcov --version
  - g++ --version
  - pyenv global $(pyenv whence 2to3)  # activate all python versions
  # Install Python virtual environment manager.
  - pip install pipenv
  - pipenv install
  - pipenv run pip install pytest

install:
  - CMAKE_BUILD_TYPE=Coverage pipenv run python setup.py develop

script:
  - CMAKE_BUILD_TYPE=Coverage pipenv run python setup.py test

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '*/tests/*' '/usr/*' '*/external/*' '/Applications/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

