language: cpp
dist: xenial
notifications:
  email: false

cache:
  directories:
    - openmpi
    - openmpi-4.0.0

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - lcov
            - g++-7
      env:
        - C_COMPILER="gcc-7"
        - CXX_COMPILER="g++-7"


before_install:
  # Disable CC and CXX, which interferes with MPI
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - lcov --version
  - gcov --version
  - g++ --version
  - pyenv global $(pyenv whence 2to3)  # activate all python versions

install:
  - bash .travis.mpi
  - pip install pipenv
  - pipenv install

script:
  - CMAKE_CXX_COMPILER=$CXX_COMPILER CMAKE_C_COMPILER=$C_COMPILER CMAKE_BUILD_TYPE=Coverage pipenv run python setup.py test

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '*/tests/*' '/usr/*' '*/external/*' '/Applications/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

