language: cpp
compiler: gcc
dist: trusty
notifications:
  email: false

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install lcov
  - gem install coveralls-lcov

before_script:
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)/project1
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build

script:
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Coverage $PARENTDIR
  - make
  - make gtest
  - make coverage

after_success:
  - lcov --list coverage.info.cleaned  # Show test report in travis log.
  - coveralls-lcov coverage.info.cleaned #--repo-token _____ coverage.info # uploads to coveralls
