language: cpp
dist: xenial
notifications:
  email: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/openmpi-build
    - $TRAVIS_BUILD_DIR/openmpi-3.1.3

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - g++-7
            - lcov
      env:
        - C_COMPILER="gcc-7", CXX_COMPILER="g++-7"

before_install:
  - pyenv global $(pyenv whence 2to3)
  - pip install pipenv
  - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/openmpi-build
  - export MPI_VERSION="3.1"
  - export MPI_FULL_VERSION="3.1.3"

install:
  # Install Python virtual environment manager.
  - source ci/install-openmpi.sh
  - $MPI_CC --version
  - $MPI_CXX --version
  - $MPI_EXEC --version
  - env MPICC=$MPI_CC pipenv install --skip-lock --pre

before_script:
  - export CMAKE_C_COMPILER=$MPI_CC
  - export CMAKE_CXX_COMPILER=$MPI_CXX
  - export CMAKE_BUILD_TYPE=Coverage

script:
  - pipenv run python setup.py test

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '*/tests/*' '/usr/*' '*/external/*' '/Applications/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

