sudo: required
language: generic
notifications:
  email: false

matrix:
  include:
    - env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev

install:
  - gem install coveralls-lcov	
  # install newer LCOV (1.9 was failing)
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install

before_script:
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build
  - lcov --directory $PARENTDIR/build --zerocounters

script:
  - cd $PARENTDIR/build
  - cmake -Dcoverage=ON -DCMAKE_CXX_COMPILER=$COMPILER $PARENTDIR/project1
  - make
  - make gtest

after_success:
  - pwd
  - lcov --directory $PARENTDIR/build --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' 'app/*' 'external/*' 'cmake/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info #--repo-token _____ coverage.info # uploads to coveralls
