language: cpp
compiler: gcc
dist: xenial
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - lcov
            - g++-7
            - gcov-7
      env:
        - CC="gcc-7"
        - CXX="g++-7"


before_install:
  # Install Python virtual environment manager.
  - lcov --version
  - gcov --version
  - g++ --version
  - pip install pipenv
  - pipenv install
  - pipenv run pip install pytest

install:
  - CMAKE_BUILD_TYPE=Coverage pipenv run python setup.py develop
  - BUILD_DIR=`find build -name 'Makefile' -not -path '*/external*' | sed 's|/[^/]*$||'`
  - cd $BUILDDIR
  - make unit_tests.x

script:
  - cd $BUILDDIR
  - ./unit_tests.x
  - cd -
  - pipenv run pytest tests

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '*/tests/*' '/usr/*' '*/external/*' '/Applications/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

